# Discord settings
discord:
  # Discord webhook URL
  # To create a webhook, see https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  # See https://discordapp.com/developers/docs/resources/webhook for more information.
  webhook-url: ''

  # This is an important field should you be using our built-in discord bot for two-way communication
  # This isn't the focus
  token: ''



# Server-Specific Options
server:

  # Server name is used in the %server_name% placeholder.
  server-name: 'Server'

  # Server prefix. Useful if you have multiple servers connected into the same channel.
  # %server_name% is the only non-placeholderAPI option here. Leave this empty to disable it.
  prefix: ''

  # Avatar used for non-chat messages and warnings.
  server-icon: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'

# Avatar API, for changing the Discord avatar per player
avatar:

  # By default we use crafatar but you can switch these options to use whichever you like. Ask in the discord for support with this.
  # %uuid% will be replaced with the user's uuid.
  url: 'https://crafatar.com/renders/head/%uuid%size=10&overlay'

# The following section toggles individual message updates when said events occur.
events:

  # We strongly suggest updating server-icon under the server section as this will be the avatar used for these events.
  # If these sections are blank they will be considered disabled. %player% and %server_name% are the only valid placeholders without PlaceholderAPI
  player-join: '%server_name% » %player% has joined the game.'
  player-leave: '%server_name% » %player% has left the game.'
  server-startup: '%server_name% has started.'
  server-shutdown: '%sever_name% has stopped.'

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the hdiscord.admin permission node
  notify: true

# Config version, no touchy plz
version: 2.3