# Thank you for using HiberniaDiscord by Paradaux.io
# Should you run into issues, feel free to pop into my discord server @ https://paradaux.io/discord
# Additional Configuration is available in locale.yml (be sure to change the response of /discord to that of your server)
# Buy me a beer: https://paypal.me/Paradaux

discord:
  # disable this if you do not wish to have HiberniaDiscord register /discord. Change the invite link in locale.yml
  discord-command: true
  # Discord webhook URL
  # To create a webhook, see https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhook-url: ''

# Server name is used in the %server_name% placeholder.
server-name: 'Server'

# Avatar API, for changing the Discord avatar per player
# By default we use crafatar but you can switch these options to use whichever you like. Ask in the discord for support with this.
# %playeruuid% will be replaced with the user's uuid.
avatar-api: 'https://crafatar.com/renders/head/%playeruuid%?size=10&overlay'

# The following section toggles individual message updates when said events occur.
events:

  # Placeholders: (Placeholder API support is baked in, if you have it installed.)
  #    * %playername% - The Player's Username
  #    * %playeruuid% - The Player's UUID
  #    * %servername% - The Server's name you specified above
  #    * %avatarapi% - The Avatar API you specified above.
  # There may be other placeholders, that are section specific such as %messageContent% referred to the content of the Message Event.
  # Empty messages will be replaced with a zero-width space so they appear as empty messages on discord.

  # Occurs when a message is sent in chat.
  chat-message:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%playername%'
    message-format: '%messageContent%'

  # Occurs when a player joins the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-join:
    enabled: true
    avatar-url: '%server_name% » %player% has joined the game.'
    username-format: '%avatarapi%'
    message-format: ''

  # Occurs when a player leaves the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-leave:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%servername% » %player% has left the game.'
    message-format: ''

  # Advancement (Achievement) Completed event. 1.16.X only.
  advancement-completed:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%player% has completed %advancement_name%'
    message-format: ''

  # Occurs when the server loads the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-startup:
    enabled: true
    avatar-url: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    username-format: '%servername% »'
    message-format: '%servername% has started.'

  # Occurs when the server disables the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-shutdown:
    enabled: true
    avatar-url: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    username-format: '%servername% »'
    message-format: '%servername% has stopped.'

settings:
  discord-command-permission: "hiberniadiscord.discord"
  reload-command-permission: "hiberniadiscord.reload"

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the hdiscord.admin permission node
  notify: true

# Config version, no touchy plz
config-version: 2.3