# Thank you for using HiberniaDiscord by Paradaux.io
# Should you run into issues, feel free to pop into my discord server @ https://paradaux.io/discord
# Additional Configuration is available in locale.yml (be sure to change the response of /discord to that of your server)

discord:
  # Discord webhook URL
  # To create a webhook, see https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhook-url: ''

# Server name is used in the %server_name% placeholder. T
server-name: 'Server'

# Avatar API, for changing the Discord avatar per player
# By default we use crafatar but you can switch these options to use whichever you like. Ask in the discord for support with this.
# %uuid% will be replaced with the user's uuid.
avatar-api: 'https://crafatar.com/renders/head/%uuid%size=10&overlay'

# The following section toggles individual message updates when said events occur.
events:

  # Occurs when a message is sent in chat.
  chat-message:
    enabled: true
    format: ''

  # Occurs when a player joins the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-join:
    enabled: true
    format: '%server_name% » %player% has joined the game.'

  # Occurs when a player leaves the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-leave:
    enabled: true
    format: '%server_name% » %player% has left the game.'

  # Occurs when the server loads the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-startup:
    enabled: true
    avatar-icon: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    format: '%server_name% has started.'

  # Occurs when the server disables the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-shutdown:
    enabled: true
    avatar-icon: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    format: '%sever_name% has stopped.'



update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the hdiscord.admin permission node
  notify: true

# Config version, no touchy plz
version: 2.3