# Copyright © 2020 Property of Rían Errity Licensed under GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007. See <LICENSE.md>
# Thank you for using HiberniaDiscord by Paradaux.io
# Should you run into issues, feel free to pop into my discord server @ https://paradaux.io/discord
# Additional Configuration is available in locale.yml (be sure to change the response of /discord to that of your server)
# Buy me a beer: https://paypal.me/Paradaux

discord:
  # disable this if you do not wish to have HiberniaDiscord register /discord. Change the invite link in locale.yml
  discord-command: true
  # Discord webhook URL
  # To create a webhook, see https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  webhook-url: ''

# Server name is used in the %server_name% placeholder.
server-name: 'Server'

# Avatar API, for changing the Discord avatar per player
# By default we use crafatar but you can switch these options to use whichever you like. Ask in the discord for support with this.
# %playeruuid% will be replaced with the user's uuid.
avatar-api: 'https://crafatar.com/renders/head/%playeruuid%?size=10&overlay'

# The following section toggles individual message updates when said events occur.
events:

  # Placeholders: (Placeholder API support is baked in, if you have it installed.)
  #    * %playername% - The Player's Username
  #    * %playeruuid% - The Player's UUID
  #    * %servername% - The Server's name you specified above
  #    * %avatarapi% - The Avatar API you specified above.
  # There may be other placeholders, that are section specific such as %messageContent% referred to the content of the Message Event.
  # Empty messages will be replaced with a zero-width space so they appear as empty messages on discord.

  # Occurs when a message is sent in chat.
  chat-message:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%playername%'
    message-format: '%messageContent%'

  # Occurs when a player joins the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-join:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%servername% »'
    message-format: '%playername% has joined the game.'

  # Occurs when a player leaves the server. Player-specific Placeholders from PlaceholderAPI are supported here.
  player-leave:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%servername% »'
    message-format: '%playername% has left the game'

  # Advancement (Achievement) Completed event. 1.16.X only.
  advancement-completed:
    enabled: true
    avatar-url: '%avatarapi%'
    username-format: '%servername% »'
    message-format: '%player% has completed %achievementName%'

  # Occurs when the server loads the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-startup:
    enabled: true
    avatar-url: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    username-format: '%servername% »'
    message-format: '%servername% has started.'

  # Occurs when the server disables the plugin. Placeholders from PlaceholderAPI are NOT supported here.
  server-shutdown:
    enabled: true
    avatar-url: 'https://cdn.paradaux.io/static/plugin-branding/hiberniadiscord/hibernia-discord.png'
    username-format: '%servername% »'
    message-format: '%servername% has stopped.'

settings:
  # Provides Additional information for debug purposes.
  debug: false

  # Provide anonymized usage stats so that I create features oriented towards my user-base
  # I won't hurt your family if you disable this, but I would appreciate you leaving it enabled.
  # It gives me information such as server versions, player counts, Java versions etcetera. Nothing identifiable.
  # You can find more information at the bottom of this configuration file.
  # https://bstats.org/plugin/bukkit/HiberniaDiscord/8386

  bstats: enabled

  # Configure the permissions HiberniaDiscord listens to.
  discord-command-permission: "hiberniadiscord.discord"
  reload-command-permission: "hiberniadiscord.reload"

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the hdiscord.admin permission node
  notify: true

# Config version, no touchy plz
config-version: 2.3

# BStats.org Notice.

# bStats does not collect any personal data. Most of the collected data is information about the plugin's server like player count, online mode,
#  Minecraft version, Java version, and more. All data gets sent and stored completely anonymously. Server IPs are only stored for ratelimiting
# and not linked to the data. All data that is collected is publicly visible. If you are interested in what data is collected for your Minecraft
# server, take a look at the pages for the plugins on your server. Please note that plugin authors can also send data that is customized for their plugin.
# https://bstats.org/plugin/bukkit/HiberniaDiscord/8386

# Force-disabling bStats

# If you don't trust me, and my settings bstats has its own system to disable plugins' bstats.

# Disabling bStats

# If you don't want bStats to collect data from your server, you can disable it in the bStats config file. This file can be found in the /plugins/bStats/ folder.
# bStats has nearly no effect on your server's performance and the sent data is completely anonymous. The collected data is important information for plugin authors
# to improve their plugins and keep motivated. To value their work and effort, please keep bStats enabled.
