version: 2.2.0
name: io.paradaux.hiberniadiscord.HiberniaDiscord
main: io.paradaux.hiberniadiscord
author: Paradaux
api-version: 1.13
description: Minecraft Chat integration for Discord. Made in Ireland.